<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('47', '/uploads/allimg/180823/19544042A-0.jpg');
$maNum = 1;
$myaddons[$maNum] = array('48', '/uploads/allimg/180823/195440I56-1.jpg');
$maNum = 2;
$myaddons[$maNum] = array('49', '/uploads/allimg/180823/1954406360-2.jpg');
$maNum = 3;
$myaddons[$maNum] = array('50', '/uploads/allimg/180823/1954401140-3.jpg');
$maNum = 4;
$myaddons[$maNum] = array('51', '/uploads/allimg/180823/1954404258-4.jpg');
$maNum = 5;
$myaddons[$maNum] = array('52', '/uploads/allimg/180823/1954405M9-5.jpg');
$maNum = 6;
