<div class="feed_tegao long" data-href="[field:typeurl/]">
    <h4>
        <a href="[field:typeurl/]"
           target="_blank">[field:title/]</a>
    </h4>
    <p class="picture"><a href="[field:arcurl/]" target="_blank"><img src="[field:picname/]" alt="[field:title/]"/></a></p>
    <p class="summary">[field:description function='cn_substr(@me,220)'/]<a href="[field:arcurl/]" class="more" target="_blank">[详情]</a></p>
    <div class="infos">
        <span class="time">[field:pubdate function='strftime("%m月%d日"，@me)'/]</span>
    </div>
</div>