<div class="related-item">
              <div class="post-thumbnail"> <a href="[filed:arcurl/]" title="[field:title/]" rel="bookmark"><img class="lazy" src="[field:picname/]" alt="[field:title/]" style="height:120px; width:180px"></a> </div>
              <a href="[field:arcurl/]" title="[field:title/]" rel="bookmark">[field:title/]</a>
              <p class="post-meta"> [field:pubdate function='strftime("%Y-%m-%d",@me)'/] </p>
            </div>