<?php
$z[0]=Array("arcurl","",40,55);
$z[1]=Array("arcurl","",86,101);
$z[2]=Array("title","",131,145);
$z[3]=Array("arcurl","",194,209);
$z[4]=Array("picname","",237,253);
$z[5]=Array("title","",260,274);
$z[6]=Array("description","",310,360);
$z[6][4]['function']="cn_substr(@me,220)";
$z[7]=Array("arcurl","",369,384);
$z[8]=Array("pubdate","",485,539);
$z[8][4]['function']="strftime(\"%m月%d日\",@me)";

?>