<li class="am-g am-list-item-desced am-list-item-thumbed am-list-item-thumb-left">
						<div class="am-u-sm-4 am-list-thumb">	<a href="[field:arcurl/]">[field:image/]</a>
						</div>
						<div class="am-u-sm-8 am-list-main">
							 <h3 class="am-list-item-hd"><a href="[field:arcurl/]">[field:title/]</a></h3>
							<div class="am-list-item-text">[field:description/]</div>
						</div>
					</li>