<li>
                <div class="relatedposts-inner">
                  <div class="relatedposts-inner-pic"> <a href="[field:arcurl/]" title="[field:title/]" class="">
                    <div class="thumb-img"> <img src="[field:picname/]" alt="[field:title/]"> <span><i class="fa fa-plus"></i></span> </div>
                    </a></div>
                  <div class="relatedposts-inner-text"> <a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a> </div>
                </div>
                <div class="clear"></div>
              </li>