<?php
$z[0]=Array("arcurl","",88,103);
$z[1]=Array("title","",112,126);
$z[2]=Array("picname","",219,235);
$z[3]=Array("title","",242,256);
$z[4]=Array("url","",358,370);
$z[5]=Array("title","",379,393);
$z[6]=Array("title","",395,409);
$z[7]=Array("pubdate","",517,569);
$z[7][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[8]=Array("click","",640,654);
$z[9]=Array("description","",726,776);
$z[9][4]['function']="cn_substr(@me,150)";

?>