<article class="home-blog-entry clr">
              <div class="thumb-title"> <a href="[field:arcurl/]" title="[field:title/]" class="fancyimg home-blog-entry-thumb">
                <div class="thumb-img"> <img src="[field:picname/]" alt="[field:title/]"> <span><i class="fa fa-plus"></i></span> </div>
                </a>
                <h3><a href="[field:url/]" title="[field:title/]">[field:title/]</a></h3>
              </div>
              <div class="postlist-meta"> <span class="postlist-meta-time">[field:pubdate function='strftime("%Y-%m-%d",@me)'/] </span> <span class="delim"></span> <span class="postlist-meta-views">[field:click/] &nbsp;℃</span> <span class="delim"></span> </div>
              <p> [field:description function='cn_substr(@me,150)'/]...</p>
            </article>