<div class="col-md-4 col-sm-4 col-xs-6 col-xxs-12 animate-box">
          <div class="img-grid"> <img src="[field:litpic /]" alt="裸食香料-[field:title function="cn_substr('@me',100)" /]" class="img-responsive"> <a title="[field:title function='html2text(@me)'/]" class="transition" href="[field:arcurl/]" target="_blank">
            <div> <span class="fh5co-meta">Nadism-裸食煮义香草料<br>
              [field:description function="cn_substr('@me',100)" /]</span>
              <h2 class="fh5co-title">[field:title/]</h2>
            </div>
            </a> </div>
        </div>