<article class="excerpt"> <a class="focus" href="[field:arcurl/]"><img src="[field:litpic/]" alt="[field:title/]"/></a>
        <header><a href="[field:typeurl/]" class="cat" title="[field:typename/]">[field:typename/]</a>
          <h2><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h2>
        </header>
        <p class="meta">
          <time>[field:pubdate function="MyDate('Y-m-d',@me)"/]</time>
          <span class="pv">阅读([field:click/])</span> </p>
        <p class="note pc"> <a href="[field:arcurl/]" title="[field:title/]">[field:description function='cn_substr(@me,200)'/]...</a></p>
      </article>