<div class="m_Grid2">
        	<div class="m_T2">

            	<p class="p4"><a href="[field:arcurl/]"><b>[field:title/]</b></a></p>
                <p class="p5">
                	<span class="c4">[field:typelink/]</span>
                    <span class="c5">[field:pubdate function=strftime('%Y.%m.%d',@me)/]</span>
                    <span class="c6">[field:click/]次浏览</span>
                </p>
            </div>
            <div class="m_Box1">
            	<a href="[field:arcurl/]"><img src="[field:litpic/]" alt="[field:title/]" height="100" width="150" /></a>
		[field:description/]...
            </div>
            <div class="d1">
            	<span class="c7">作者：[field:writer /]</span>
                <span class="c8">标签：
                [field:id function=GetTags(@me)/]
            	</span><div class="c9"><a title="[field:title function='htmlspecialchars(@me)'/]" href="[field:arcurl/]">阅读全文</a></div>
            </div>
            </div>