<?php
$z[0]=Array("list","<url>	\n   <loc>[field:arcurl function=\"Gmapurl(@me)\"/]</loc> 	\n   <title>[field:title function=\"HtmlReplace(@me)\"/]</title>	\n   <news:news>	\n  <news:keywords>[field:keywords/]</news:keywords>	\n <news:publication_date>[field:senddate function=\"strftime(\"%Y-%m-%d\",@me)\"/]</news:publication_date>	\n </news:news>	\n</url>",0,440);
$z[0][4]['pagesize']="500";
$z[0][4]['col']="1";
$z[0][4]['titlelen']="60";
$z[0][4]['orderby']="pubdate";
$z[0][4]['orderway']="desc";
$z[0][4]['channel']="1";
$z[0][4]['keyword']="";

?>