<?php
$z[0]=Array("typeurl","",40,56);
$z[1]=Array("typeurl","",87,103);
$z[2]=Array("title","",133,147);
$z[3]=Array("arcurl","",196,211);
$z[4]=Array("picname","",239,255);
$z[5]=Array("title","",262,276);
$z[6]=Array("description","",312,362);
$z[6][4]['function']="cn_substr(@me,220)";
$z[7]=Array("arcurl","",371,386);
$z[8]=Array("pubdate","",487,548);
$z[8][4]['function']="strftime(\"%Y年%m月%d日\"，@me)";

?>