<li> <a class="slider-img" href="[field:typeurl/]" title="[field:typename/]"> <img src="[field:picname/]" alt="[field:title/]"/></a>
              <div class="slider-text">
                <div class="cl">
                  <div class="slider-meta"> <span class="num">0[field:global.autoindex/]</span> <span class="author">[field:writer/]</span> <span class="date">[field:pubdate function='strftime("%m-%d",@me)'/]</span> </div>
                  <h2><a href="[field:typeurl/]" title="[field:title/]">[field:title/]</a></h2>
                </div>
                <span class="slider-excerpt"><br/>
                [field:description function='cn_substr(@me,220)'/]</span> <span class="slider-readmore"><a href="[field:arcurl/]" title="[field:title/]" target="_blank">Read More »</a></span> </div>
            </li>