<div class="panel panel-default w_article_item">
									<div class="panel-body ">
										<div class="row">
										  <div class="col-xs-6 col-md-3">
										    <a href="#" class="thumbnail w_thumbnail">
										      <img src="[field:picname/]" alt="[field:title/]">
										    </a>
										  </div>
										  <h4 class="media-heading">
										  	<a class="title" href="[field:arcurl/]">[field:title/]</a>
										  </h4>
										  <p></p>
										  <p class="w_list_overview overView">[field:description function='cn_substr(@me,220)'/]。。。</p>
										  <p class="count_r"><span class="count"><i class="glyphicon glyphicon-user"></i><a href="#">[field:writer/]</a></span> <span class="count"><i class="glyphicon glyphicon-eye-open"></i>阅读:[field:click/]</span><span class="count"><i class="glyphicon glyphicon-comment"></i>评论:2</span><span class="count"><i class="glyphicon glyphicon-time"></i>[field:pubdate function='strftime("%Y-%m-%d",@me)'/]</span></p>
										</div>
									</div>
								</div>