<article class="home-blog-entry col span_1 clr"> <a href="[field:arcurl/]" title="[field:title/]" class="fancyimg home-blog-entry-thumb">
            <div class="thumb-img2"> <img src="[field:picname/]" alt="[field:title/]"> <span><i class="fa fa-plus"></i></span> </div>
            </a>
            <div class="home-blog-entry-text clr">
              <h3> <a href="[field:arcurl/]" title="[field:title/]"><b>[field:title/]</b></a> </h3>
              <!-- Post meta -->
              <div class="meta"> <span class="postlist-meta-time"><i class="fa fa-calendar"></i>[field:pubdate function='strftime("%Y-%m-%d",@me)'/]</span> <span class="postlist-meta-views"><i class="fa fa-fire"></i>浏览: [field:click/] </span> <span class="postlist-meta-comments"><i class="fa fa-folder-open"></i> <a href="[field:typeurl/]"><span>栏目: </span>[field:typename/]</a></span> </div>
              <!-- /.Post meta --> 
              <br>
              <p> [field:description function='cn_substr(@me,220)'/]... </p>
            </div>
            <div class="clear"></div>
          </article>