<?php
$z[0]=Array("arcurl","",58,73);
$z[1]=Array("title","",82,96);
$z[2]=Array("picname","",186,202);
$z[3]=Array("title","",209,223);
$z[4]=Array("arcurl","",372,387);
$z[5]=Array("title","",396,410);
$z[6]=Array("title","",415,429);
$z[7]=Array("pubdate","",575,627);
$z[7][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[8]=Array("click","",703,717);
$z[9]=Array("typeurl","",806,822);
$z[10]=Array("typename","",845,862);
$z[11]=Array("description","",957,1007);
$z[11][4]['function']="cn_substr(@me,220)";

?>