<li>
          <div class="tab-item-thumbnail"> <a href="[field:arcurl/]" title="[field:title/]">
            <div class="thumb-img"> <img src="[field:picname/]" /> <span><i class="fa fa-plus"></i></span> </div>
            </a> </div>
          <div class="tab-item-inner group">
            <p class="tab-item-title"><a href="[field:arcurl/]"  title="[field:title/]">[field:title/]</a></p>
            <span class="tab-item-date">[field:pubdate function='strftime("%Y-%m-%d",@me)'/] </span>&nbsp; <span class="tab-item-category"><a href="[field:typeurl/]" >[field:typename/]</a></span> </div>
        </li>