<?php
$z[0]=Array("arcurl","",79,94);
$z[1]=Array("title","",103,117);
$z[2]=Array("picname","",145,161);
$z[3]=Array("title","",168,182);
$z[4]=Array("arcurl","",219,234);
$z[5]=Array("title","",243,257);
$z[6]=Array("title","",275,289);
$z[7]=Array("writer","",375,390);
$z[8]=Array("pubdate","",455,502);
$z[8][4]['function']="MyDate('Y-m-d',@me)";
$z[9]=Array("click","",560,574);
$z[10]=Array("description","",634,684);
$z[10][4]['function']="cn_substr(@me,320)";

?>