<section class="section wow fadeIn">
        <div class="thumbnail"> <a href="[field:arcurl/]" title="[field:title/]" target="_blank"><img src="[field:picname/]" alt="[field:title/]"/></a> </div>
        <h2><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h2>
        <div class="postmeta"> <span><i class="icon-user-circle-o"></i> <a>[field:writer/]</a></span> <span><i class="icon-calendar"></i>
          <time>[field:pubdate function="MyDate('Y-m-d',@me)"/]</time>
          </span> <span><i class="icon-eye"></i> [field:click/]</span></div>
        <div class="excerpt">
          <p> [field:description function="cn_substr(@me,320)"/]...</p>
        </div>
      </section>