<?php
$z[0]=Array("pubdate","",83,244);
$z[0][4]['function']="strftime(\"%F\",@me)";
$z[0][4]['</div> <header class']="tit";
$z[0][4]['> <h2 class']="h1";
$z[0][4]['> <a href']="[field:arcurl";
$z[1]=Array("title","",253,267);
$z[2]=Array("title","",269,283);
$z[3]=Array("typeurl","",411,427);
$z[4]=Array("typename","",436,453);
$z[5]=Array("typename","",470,487);
$z[6]=Array("click","",570,584);
$z[7]=Array("arcurl","",702,717);
$z[8]=Array("title","",741,755);
$z[9]=Array("picname","",776,792);
$z[10]=Array("title","",799,813);
$z[11]=Array("description","",815,865);
$z[11][4]['function']="cn_substr(@me,220)";
$z[12]=Array("arcurl","",889,904);

?>