<?php
$z[0]=Array("arcurl","",9,24);
$z[1]=Array("title","",42,56);
$z[2]=Array("writer","",129,145);
$z[3]=Array("pubdate","",169,215);
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",256,270);
$z[5]=Array("litpic","",347,362);
$z[6]=Array("title","",369,383);
$z[7]=Array("info","",440,484);
$z[7][4]['function']="cn_substr(@me,360)";
$z[8]=Array("id","",541,574);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",622,637);
$z[10]=Array("click","",657,671);

?>