<A href="[field:arcurl/]" target="_blank">[field:title/]</A>
 	
				
            </h2>
            <p><span class="c1">作者：[field:writer /]</span><span class="c2">[field:pubdate function="GetDateTimeMK(@me)"/]</span></p>
            <div class="c3">[field:click/] ℃</div>
        </div>
        <div class="m_Grid1">
        	<img src="[field:litpic/]" alt="[field:title/]" height="400" width="610" />
            <p class="p1">[field:info  function="cn_substr(@me,360)"/] ...</p>
            <p class="p2"><span>标签：</span>
[field:id function=GetTags(@me)/]
			</p>

            <p class="p3"><a href="[field:arcurl/]" target="_blank">共[field:click/]人看过，阅读全文>></a></p>