<li> <a href="[field:arcurl/]" target="_blank"  title="[field:title/]"> <img src="[field:picname/]"  alt="[field:title/]" /> </a>
          <div class="flex-caption">
            <h2><a href="[field:arcurl/]"  target="_blank" >[field:title/]</a></h2>
            <p class="slides_entry">[field:description function="cn_substr(@me,220)"/]... </p>
            <p class="btn"><a href="[field:arcurl/]"  target="_blank" >查看详情</a></p>
          </div>
        </li>