<li class="list_new cl">
  <h2><a href="[field:arcurl/]" target="_blank" title="[field:title/]">[field:title/]</a></h2>
  <div class="con cl"> 
  <div class="pic">
  <a href="[field:arcurl/]" target="_blank" title="[field:title/]"><img src="[field:picname/]" widath="260" height="180" alt="[field:title/]"></a>
  </div>
  <p class="sum">[field:info function="cn_substr（@me,250）"/]... </p>
    <p class="time">更新时间：<span title="[field:pubdate function="GetDateTimeMK(@me)"/] ">[field:pubdate function="GetDateTimeMK(@me)"/] </span> - 阅读次数 : [field:click/] <br>标签：<a href="#">[field:id function=GetTags(@me)/]</a> </p>
<em class="move"><a href="[field:arcurl/]" target="_blank">阅读更多</a></em>
  </div>
</li>