<?php
$z[0]=Array("arcurl","",46,61);
$z[1]=Array("id","  \r\n    global \$dsql;\r\n    \$id = @me;\r\n    \$sql='select slider_img from dede_archives where id='.\$id;\r\n    \$row=\$dsql->getone(\$sql);\r\n    @me=\$row['slider_img'];\r\n ",86,282);
$z[1][4]['runphp']="yes";
$z[2]=Array("title","",289,303);
$z[3]=Array("title","",366,380);
$z[4]=Array("description","",402,451);
$z[4][4]['function']="cn_substr(@me,90)";

?>