<?php
$z[0]=Array("arcurl","",79,94);
$z[1]=Array("title","",103,117);
$z[2]=Array("picname","",145,161);
$z[3]=Array("title","",168,182);
$z[4]=Array("arcurl","",219,234);
$z[5]=Array("title","",243,257);
$z[6]=Array("title","",275,289);
$z[7]=Array("description","",345,395);
$z[7][4]['function']="cn_substr(@me,320)";
$z[8]=Array("writer","",495,510);
$z[9]=Array("pubdate","",575,622);
$z[9][4]['function']="MyDate('Y-m-d',@me)";
$z[10]=Array("click","",680,694);

?>