<?php
$z[0]=Array("title","",56,70);
$z[1]=Array("arcurl","",78,93);
$z[2]=Array("litpic","",106,121);
$z[3]=Array("title","",128,142);
$z[4]=Array("arcurl","",247,262);
$z[5]=Array("title","",286,300);
$z[6]=Array("title","",318,332);
$z[7]=Array("pubdate","",444,495);
$z[7][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[8]=Array("click","",566,580);
$z[9]=Array("description","",640,660);
$z[10]=Array("arcurl","",693,708);
$z[11]=Array("title","",717,731);
$z[12]=Array("typelink","",975,992);
$z[13]=Array("id","",1053,1086);
$z[13][4]['function']="GetTags(@me)";

?>