<div class="box">
        <div class="post"> <a title="[field:title/]" href="[field:arcurl/]" ><img src="[field:litpic/]" alt="[field:title/]" class="thumbnail alignleft"  height="200"  width="200"    /></a>
          <h2 class="title"><a href="[field:arcurl/]" rel="bookmark" title="[field:title/]" target="_blank">[field:title/]</a></h2>
          <p class="post-meta" style="padding-top:10px;"> <img src="/skin/img/ico-time.png" alt="" />[field:pubdate function="MyDate('Y-m-d H:i',@me)"/] <span class="comments"><img src="/skin/img/ico-comment.png" alt="" /> [field:click/]</span> </p>
          <div class="entry">
            <p>[field:description/]</p>
            <span><a href="[field:arcurl/]" title="[field:title/]"  class="readmore" target="_blank">>>阅读全文及试听</a></span> </div>
          <div class="fix"></div>
        </div>
        <!-- /.post -->
        
        <div class="post-bottom">
          <div class="fl"><span class="cat">[field:typelink/]</span></div>
          <div class="fr"><span class="tags"> [field:id function=GetTags(@me)/]</span></div>
          <div class="fix"></div>
        </div>
      </div>
      <!-- /.box -->