<?php
$z[0]=Array("arcurl","",47,62);
$z[1]=Array("title","",71,85);
$z[2]=Array("picname","",176,192);
$z[3]=Array("title","",199,213);
$z[4]=Array("arcurl","",311,326);
$z[5]=Array("title","",335,349);
$z[6]=Array("title","",351,365);
$z[7]=Array("pubdate","",472,524);
$z[7][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[8]=Array("click","",587,601);
$z[9]=Array("description","",636,686);
$z[9][4]['function']="cn_substr(@me,220)";

?>