<li class="archive-thumb">
                <article>
                  <h2><a href="[field:arcurl/]" title="">[field:title/]</a></h2>
                  <a class="pic float-left" href="[field:arcurl/]" title=""> <img class="lazy" src="[field:picname/]" style="height:120px; width:180px"></a>
                  <p> [field:description function='cn_substr(@me,250)'/]... </p>
                  <p class="post-meta"> <span><i class="icon-user"></i>[field:writer/]</span><span><i class="icon-time"></i>[field:pubdate function='strftime("%Y-%m-%d",@me)'/]</span><span><i class="icon-eye-open"></i>[field:click/]</span><span></span> </p>
                  <div class="clear"> </div>
                </article>
              </li>