<article class="excerpt">
      <header> <a class="label label-important" href="[field:typeurl/]"> [field:typename/]<i class="label-arrow"> </i> </a>
        <h2> <a target="_blank" href="[field:arcurl/]" title=""> [field:title/] </a> </h2>
      </header>
      <div class="focus"> <a target="_blank" href="[field:arcurl/]"> <img class="thumb" src="[field:litpic/]" alt="[field:title/]"> </a> </div>
      <span class="note"> [field:description function='cn_substr(@me,250)'/]... </span>
      <p class="auth-span"> <span class="muted"> <i class="fa fa-clock-o"> </i> [field:pubdate function='strftime("%Y-%m-%d",@me)'/] </span> <span class="muted"> <i class="fa fa-eye"> </i> [field:click/]℃ </span> <!-- <span class="muted"> <i class="fa fa-comments-o"> </i> <a target="_blank" href="[field:arcurl/]#comments"> 
        <script src="/plus/pls.php?aid=164" language="javascript"></script>评论 </a> </span> <span class="muted" id="diggNum164"> <a id="Addlike" class="action" href="javascript:" onclick="javascript:postDigg('good',164)"> <i class="fa fa-heart-o"> </i> <span class="count"> 3 </span> 喜欢 </a> </span>--> </p>
    </article>