<?php
$z[0]=Array("typeurl","",81,97);
$z[1]=Array("typename","",100,117);
$z[2]=Array("arcurl","",190,205);
$z[3]=Array("title","",217,231);
$z[4]=Array("arcurl","",312,327);
$z[5]=Array("litpic","",354,369);
$z[6]=Array("title","",376,390);
$z[7]=Array("description","",432,482);
$z[7][4]['function']="cn_substr(@me,250)";
$z[8]=Array("pubdate","",575,627);
$z[8][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[9]=Array("click","",684,698);
$z[10]=Array("arcurl","",795,810);

?>