<article class="clr col-small"> <a href="[field:arcurl/]" title="[field:title/]" class="fancyimg home-blog-entry-thumb">
              <div class="thumb-img"> <img src="[field:picname/]" alt="[field:title/]"> <span><i class="fa fa-plus"></i></span> </div>
              </a>
              <h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
              <p> [field:description function="cn_substr(@me,150)"]... </p>
            </article>