<li class="post box row ">
        <div class="thumbnail"> <a href="[field:arcurl/]" class="zoom"  target="_blank" title="[field:title/]"> <img src="[field:picname/]" alt="[field:title/]" />
          <div class="zoomOverlay"></div>
          </a> </div>
        <div class="article">
          <h2><a href="[field:arcurl/]"  target="_blank" title="[field:title/]">[field:title/]</a></h2>
        </div>
        <div class="info"> <span class="info_date info_ico">[field:pubdate function='strftime("%m-%d",@me)'/]</span> <span class="info_views info_ico">[field:click/] </span> 
          <!--评论数 <span class="info_comment info_ico"><a href="#">88</a></span>--> 
          <span class="info_category info_ico"><a href="[field:typeurl/]" rel="category">[field:typename/]</a></span> </div>
      </li>