<?php
$z[0]=Array("arcurl","",69,84);
$z[1]=Array("title","",123,137);
$z[2]=Array("picname","",150,166);
$z[3]=Array("title","",173,187);
$z[4]=Array("arcurl","",313,328);
$z[5]=Array("title","",354,368);
$z[6]=Array("title","",370,384);
$z[7]=Array("pubdate","",471,520);
$z[7][4]['function']="strftime(\"%m-%d\",@me)";
$z[8]=Array("click","",562,576);
$z[9]=Array("typeurl","",734,750);
$z[10]=Array("typename","",767,784);

?>