<?php
$z[0]=Array("field","",92,121);
$z[0][4]['name']="typelink";
$z[1]=Array("field","",130,159);
$z[1][4]['name']="typename";
$z[2]=Array("field","",185,214);
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\r\n        <h2 class=\"entry-title\"><a href=\"[field:arcurl/]\" rel=\"bookmark\" title=\"[field:title/]\">[field:title/]</a></h2>\r\n          <figure class=\"thumbnail\"> <a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\"  alt=\"[field:title/]\" /></a> </figure>\r\n          <div class=\"cat-main\">[field:description function=\"cn_substr(@me,220)\"/]...</div>\r\n        ",302,736);
$z[3][4]['row']="1";
$z[3][4]['titlelen']="80";
$z[3][4]['limit']="1,2";
$z[3][4]['orderby']="click";
$z[4]=Array("arclist","\r\n          <span class=\"list-date\">[field:pubdate function='strftime(\"%m-%d\",@me)']</span>\r\n          <li class=\"list-title\"><a href=\"[field:arcurl/]\" rel=\"bookmark\" title=\"[field:title/]\">[field:title/]</a></li>\r\n          ",822,1126);
$z[4][4]['row']="1";
$z[4][4]['titlelen']="80";
$z[4][4]['limit']="1,2";
$z[4][4]['orderby']="click";

?>