<?php
$z[0]=Array("typeurl","",64,80);
$z[1]=Array("typename","",102,119);
$z[2]=Array("arcurl","",173,188);
$z[3]=Array("title","",209,223);
$z[4]=Array("arcurl","",312,327);
$z[5]=Array("title","",336,350);
$z[6]=Array("litpic","",393,408);
$z[7]=Array("description","",548,598);
$z[7][4]['function']="cn_substr(@me,250)";
$z[8]=Array("pubdate","",681,733);
$z[8][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[9]=Array("arcurl","",788,803);
$z[10]=Array("click","",907,921);
$z[11]=Array("arcurl","",971,986);
$z[12]=Array("title","",995,1009);

?>