<?php
$z[0]=Array("typeurl","",64,80);
$z[1]=Array("typename","",102,119);
$z[2]=Array("arcurl","",173,188);
$z[3]=Array("title","",209,223);
$z[4]=Array("arcurl","",312,327);
$z[5]=Array("title","",336,350);
$z[6]=Array("litpic","",393,408);
$z[7]=Array("description","",551,601);
$z[7][4]['function']="cn_substr(@me,250)";
$z[8]=Array("pubdate","",688,740);
$z[8][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[9]=Array("arcurl","",795,810);
$z[10]=Array("click","",914,928);
$z[11]=Array("arcurl","",978,993);
$z[12]=Array("title","",1002,1016);

?>