<div class="block">
      <h2><span class="category"> <a href="[field:typeurl/]" rel="category tag" >[field:typename/]</a> <i class="fa fa-caret-right"></i></span><a href="[field:arcurl/]"  target="_ablank" >[field:title/]</a></h2>
      <div class="clear"></div>
      
      <div class='viewimg'> <a href='[field:arcurl/]' title='[field:title/]' target='_ablank' class='ipic'> <img src='[field:litpic/]' class='thumbnail' /><span class='shine' style='background-position: 160px 50%;'> </span></a> </div>
      
      <div class="preview"> <p>[field:description function='cn_substr(@me,250)'/]...</p> </div>
      <div class="preem"> <span><i class="fa fa-clock-o"></i> 日期：[field:pubdate function='strftime("%Y-%m-%d",@me)'/] </span><span><i class="fa fa-comment-o"></i> <a href="[field:arcurl/]" class="ds-thread-count" data-thread-key="156">暂无评论</a> </span><span><i class="fa fa-eye"></i> [field:click/] </span><span> </span><span class="more"><a href="[field:arcurl/]" title="[field:title/]">阅读详情</a></span> </div>
    </div>