<?php
$z[0]=Array("arcurl","",192,207);
$z[1]=Array("picname","",220,236);
$z[2]=Array("title","",243,257);
$z[3]=Array("typelink"," @me =str_replace('[','',str_replace(']','',@me)); ",284,381);
$z[3][4]['runphp']="yes";
$z[4]=Array("arcurl","",482,497);
$z[5]=Array("title","",532,546);
$z[6]=Array("description","",653,673);
$z[7]=Array("pubdate","",783,833);
$z[7][4]['function']="strftime('%Y.%m.%d',@me)";
$z[8]=Array("arcurl","",952,967);

?>