<?php
$z[0]=Array("field","",70,99);
$z[0][4]['name']="typename";
$z[1]=Array("field","",134,157);
$z[1][4]['name']="id";
$z[2]=Array("field","",166,195);
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\r\n    <li><a title=\"[field:title/]\" href=\"view.php?aid=[field:id/]\"><i></i>[field:title/]</a></li>\r\n    ",228,402);
$z[3][4]['orderby']="pubdate";
$z[3][4]['titlelen']="38";
$z[3][4]['row']="8";

?>