<?php
$z[0]=Array("arcurl","",49,64);
$z[1]=Array("title","",77,91);
$z[2]=Array("picname","",98,114);
$z[3]=Array("arcurl","",181,196);
$z[4]=Array("title","",224,238);
$z[5]=Array("typename","",312,329);
$z[6]=Array("pubdate"," \$today = Floor(time()/(3600 * 24)); \$senday= Floor(@me/(3600 * 24)); \r\n            \$updays = \$today-\$senday; \r\n            if(\$updays==0) @me = \"今日\"; else @me = \$updays.\"天前\"; ",424,652);
$z[6][4]['runphp']="yes";
$z[7]=Array("writer","",719,734);
$z[8]=Array("click","",833,847);

?>