<?php
$z[0]=Array("arcurl","",109,124);
$z[1]=Array("title","",126,140);
$z[2]=Array("description","",202,252);
$z[2][4]['function']="cn_substr(@me,220)";
$z[3]=Array("writer","",341,356);
$z[4]=Array("click","",435,449);
$z[5]=Array("pubdate","",516,568);
$z[5][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[6]=Array("arcurl","",673,688);
$z[7]=Array("picname","",746,762);
$z[8]=Array("title","",769,783);

?>