<?php
$z[0]=Array("arcurl","",9,24);
$z[1]=Array("title","",42,56);
$z[2]=Array("writer","",132,148);
$z[3]=Array("pubdate","",172,218);
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",259,273);
$z[5]=Array("litpic","",351,366);
$z[6]=Array("title","",373,387);
$z[7]=Array("info","",444,488);
$z[7][4]['function']="cn_substr(@me,360)";
$z[8]=Array("id","",548,581);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",629,644);
$z[10]=Array("click","",665,679);

?>