<?php
$z[0]=Array("arcurl","",111,126);
$z[1]=Array("title","",128,142);
$z[2]=Array("description","",197,247);
$z[2][4]['function']="cn_substr(@me,220)";
$z[3]=Array("writer","",336,351);
$z[4]=Array("click","",430,444);
$z[5]=Array("pubdate","",511,563);
$z[5][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[6]=Array("arcurl","",687,702);
$z[7]=Array("picname","",760,776);
$z[8]=Array("title","",783,797);

?>