<?php
$z[0]=Array("field","",30,76);
$z[0][4]['name']="id";
$z[0][4]['runphp']="yes";
$z[0][4]['@me']="d";
$z[1]=Array("field","",230,260);
$z[1][4]['name']="typelink";
$z[2]=Array("field","",262,292);
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\r\n              <li class=\"first-posts\"><a href=\"[field:arcurl/]\"class=\"post-thumbnail\"title=\"[field:title/]\"rel=\"bookmark\"><img src=\"[field:picname/]\"alt=\"[field:title/]\"style=\"height:120px; width:180px\"/></a>\r\n                <h3><a href=\"[field:arcurl/]\"title=\"[field:title/]\"rel=\"bookmark\">[field:title/]</a></h3>\r\n                <p class=\"summary\"> [field:description function=\"cn_substr(@me,220)\"/]...</p>\r\n              </li>\r\n              ",394,907);
$z[3][4]['titlelen']="80";
$z[3][4]['row']="1";
$z[3][4]['limit']="0,1";
$z[4]=Array("arclist","\r\n              <li class=\"other-news\"><span>[field:pubdate function='strftime(\"%m-%d\",@me)'/]</span><a href=\"[field:arcurl/]\"title=\"[field:title/]\"><i class=\"icon-angle-right\"></i>[field:title/]</a></li>\r\n               ",967,1253);
$z[4][4]['titlelen']="80";
$z[4][4]['row']="5";
$z[4][4]['limit']="2,7";

?>