<div class="panel panel-default">
										<div class="panel-body">
											<div class="contentleft">
											<h4><a class="title" href="[field:arcurl/]">[field:title/]</a></h4>
											<p></p>
											<p class="overView">[field:description function='cn_substr(@me,220)'/]。。。</p>
											<p><span class="count"><i class="glyphicon glyphicon-user"></i>[field:writer/]</span> <span class="count"><i class="glyphicon glyphicon-eye-open"></i>阅读:[field:click/]</span><span class="count"><i class="glyphicon glyphicon-time"></i>[field:pubdate function='strftime("%Y-%m-%d",@me)'/]</span></p>
										</div>
											<div class="contentImage">
												<div class="row">
													<a href="[field:arcurl/]" class="thumbnail w_thumbnail">
														<img src="[field:picname/]" alt="[field:title/]">
													</a>
												</div>
										</div>
										</div>
										
									</div>