<?php
$z[0]=Array("arcurl","",147,162);
$z[1]=Array("title","",164,178);
$z[2]=Array("description","",240,290);
$z[2][4]['function']="cn_substr(@me,220)";
$z[3]=Array("writer","",379,394);
$z[4]=Array("click","",473,487);
$z[5]=Array("pubdate","",554,606);
$z[5][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[6]=Array("arcurl","",729,744);
$z[7]=Array("picname","",802,818);
$z[8]=Array("title","",825,839);

?>