<?php
$z[0]=Array("channel","<a href='[field:typeurl/]'>[field:typename/]</a>|",63,152);
$z[0][4]['type']="son";
$z[1]=Array("field","",175,203);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",255,283);
$z[2][4]['name']="typeurl";
$z[3]=Array("field","",285,314);
$z[3][4]['name']="typename";
$z[4]=Array("arclist","\r\n        	<li>\r\n            	<a href=\"[field:arcurl/]\">[field:title/]</a>\r\n                [field:description function=\"cn_substr(@me,70)\"/]...\r\n            </li>\r\n        	",404,649);
$z[4][4]['limit']="0,2";
$z[4][4]['titlelen']="50";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("arclist","\r\n			<li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n			",704,838);
$z[5][4]['limit']="2,6";
$z[5][4]['titlelen']="50";
$z[5][4]['orderby']="pubdate";
$z[6]=Array("arclist","\r\n        <h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n		<p>[field:description function=\"cn_substr(@me,130)\"/]……</p>\r\n        ",901,1097);
$z[6][4]['row']="1";
$z[6][4]['titlelen']="50";
$z[6][4]['flag']="a";
$z[7]=Array("arclist","\r\n			<li>\r\n                <a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" alt=\"[field:fulltitle/]\" /></a>\r\n                <h4><em>【推荐】</em><a href=\"[field:arcurl/]\">[field:fulltitle/]</a></h4>\r\n                <p>[field:description function=\"cn_substr(@me,100)\"/]...</p>\r\n            </li>\r\n			",1137,1504);
$z[7][4]['row']="3";
$z[7][4]['titlelen']="100";
$z[7][4]['flag']="c";
$z[8]=Array("arclist","\r\n			<li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n			",1642,1770);
$z[8][4]['row']="10";
$z[8][4]['titlelen']="100";
$z[8][4]['orderby']="click";

?>