<div class="img-text-list">
        <div class="img-text-list-left"><a title="[field:title/]" href="[field:arcurl/]" target="_blank"><img alt="[field:title/]" src="[field:picname/]"></a></div>
        <div class="img-text-list-right">
          <h4><i class="dot-icon2"></i><a title="[field:title/]" href="[field:arcurl/]" target="_blank">[field:title/]</a></h4>
          <div>
            <p>[field:description function="cn_substr(@me,200)"/]...</p>
            <a title="[field:title/]" href="[field:arcurl/]" target="_blank" class="more-text-item">【更多】</a> </div>
        </div>
      </div>