<article class="excerpt list5">
        <p class="image-container"><a target="_blank" class="focus" href="[field:arcurl/]"><img src="[field:picname/]" class="thumb"></a></p>
        <header>
          <h2><a target="_blank" href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h2>
        </header>
        <p class="meta">
          <time><i class="fa fa-clock-o"></i>[field:pubdate function='%Y-%m-%d,@me'/]</time>
          <span class="pv"><i class="fa fa-eye"></i>浏览:[field:click/]次</span></p>
      </article>