<?php
$z[0]=Array("arcurl","",28,43);
$z[1]=Array("title","",51,65);
$z[2]=Array("id","  \r\n        global \$dsql;\r\n        \$id = @me;\r\n        \$sql='select slider_img from dede_archives where id='.\$id;\r\n        \$row=\$dsql->getone(\$sql);\r\n        @me=\$row['slider_img'];\r\n     ",77,297);
$z[2][4]['runphp']="yes";
$z[3]=Array("title","",306,320);
$z[4]=Array("title","",327,341);
$z[5]=Array("title","",401,415);

?>