<?php
$z[0]=Array("id","",33,44);
$z[1]=Array("title","",53,68);
$z[2]=Array("title","",108,123);
$z[3]=Array("pubdate","",156,203);
$z[3][4]['function']="MyDate('Y-m-d',@me)";
$z[4]=Array("description","",235,284);
$z[4][4]['function']="cn_substr(@me,70)";
$z[5]=Array("typename","",373,390);
$z[6]=Array("global","",398,421);
$z[6][4]['name']="cfg_mip";
$z[7]=Array("typeid","",436,451);
$z[8]=Array("typename","",473,490);

?>