<?php
$z[0]=Array("arcurl","",58,73);
$z[1]=Array("title","",82,96);
$z[2]=Array("picname","",146,162);
$z[3]=Array("arcurl","",333,348);
$z[4]=Array("title","",358,372);
$z[5]=Array("title","",374,388);
$z[6]=Array("pubdate"," </span>&nbsp; <span class=\"tab-item-category\"><a href=\"[field:typeurl",438,561);
$z[6][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[7]=Array("typename","",564,581);

?>