<li class="am-g am-list-item-desced am-list-item-thumbed am-list-item-thumb-left">
								<div class="am-u-sm-4 am-list-thumb">
									<a href="view.php?aid=[field:id/]">
										<img src="[field:litpic/]" width="75px" height="75px">
									</a>
								</div>
								<div class=" am-u-sm-8 am-list-main">
									 <h3 class="am-list-item-hd">
            <a href="view.php?aid=[field:id/]" class="">[field:title/]</a>
          </h3>
									<div class="am-list-item-text"><b>日期：</b>[field:pubdate function="GetDateTimeMK(@me)"/] <b>点击：</b>[field:click/] <b>好评：</b>[field:scores/]</div>
									<p class="intro">[field:description/]...</p>
								</div>
							</li>