<div class="item item[field:global name=autoindex runphp="yes"]@me=@me-1;[/field:global] col-md-3 ThemeFborder">
                          
<div class="thumbnail Themebghover">
                              
<a title="[field:title/]" href="[field:arcurl/]">
 <img alt="[field:title/]" data-original="[field:litpic/]" alt="[field:title/]" style=" width:233px; height:143px;">
                                         
                              </a>
                          
</div>
                          
<div class="text">
                            <h3>[field:title/]</h3>
                            <p class="time">[field:pubdate   function=mydate('Y-m-d',@me)/]</p>
                          
</div>
                          
<div class="cl">
</div>
                        
</div>