<li class="first-posts"><a href="[field:arcurl/]"class="post-thumbnail"title="[field:title/]"rel="bookmark"><img src="[field:picname/]"alt="[field:title/]"style="height:120px; width:180px"/></a>
                <h3><a href="[field:arcurl/]"title="[field:title/]"rel="bookmark">[field:title/]</a></h3>
                <p class="summary"> [field:description function="cn_substr(@me,220)"/]...</p>
              </li>