<?php
$z[0]=Array("arclist","\r\n          <li><span class=\"li-icon li-icon-[field:global.autoindex/]\">[field:global.autoindex/]</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n          ",226,447);
$z[0][4]['orderby']="click";
$z[0][4]['row']="10";
$z[1]=Array("arclist","\r\n         <li><a href=\"[dede:arcurl/]\">[field:title/]</a></li>\r\n          ",898,1026);
$z[1][4]['orderby']="rand";
$z[1][4]['row']="10";

?>