<article id="post-6683" class="post-6683 post type-post status-publish format-standard hentry category-wordpress tag-wordpress">
        <figure class="thumbnail box-hide box-show"> <a href="[field:arcurl/]"> <img src="[field:picname/]" alt="[field:title/]"> </a> <span class="cat"> [field:typelink runphp='yes'] @me =str_replace('[','',str_replace(']','',@me)); [/field:typelink]</span> </figure>
        <header class="entry-header">
          <h2 class="entry-title"><a href="[field:arcurl/]" rel="bookmark">[field:title/]</a></h2>
        </header>
        <div class="entry-content">
          <div class="archive-content"> [field:description/]...</div>
          <br>
          <span class="title-l"></span><span class="entry-meta"><span class="date">[field:pubdate function=strftime('%Y.%m.%d',@me)/]&nbsp;</span> </span>
          <div class="clear"></div>
        </div>
        <span class="entry-more"> <a href="[field:arcurl/]" rel="bookmark">阅读全文</a></span></article>