<li class="col-pro item[field:global name=autoindex runphp="yes"]@me=@me-1;[/field:global]" >
                        
<div class="thumbnail Themebghover">
                            
<a title="[field:title/]" href="[field:arcurl/]">
                                
<div class="pro_face">
 <img alt="[field:title/]" data-original="[field:litpic/]"  style=" width:233px; height:160px;">
                                 
                                
</div>  
                                
<div class="text">[field:title/]
</div>     
                            </a>    
                        
</div>     
                      </li>