<?php
$z[0]=Array("typeurl","",81,97);
$z[1]=Array("typename","",99,116);
$z[2]=Array("arcurl","",189,204);
$z[3]=Array("title","",213,227);
$z[4]=Array("title","",230,244);
$z[5]=Array("arcurl","",324,339);
$z[6]=Array("litpic","",366,381);
$z[7]=Array("title","",388,402);
$z[8]=Array("description","",444,494);
$z[8][4]['function']="cn_substr(@me,220)";
$z[9]=Array("pubdate","",587,639);
$z[9][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[10]=Array("click","",696,710);

?>