<article class="excerpt">
      <header> <a class="label label-important" href="[field:typeurl/]">[field:typename/]<i class="label-arrow"> </i> </a>
        <h2> <a target="_blank" href="[field:arcurl/]" title="[field:title/]"> [field:title/]</a> </h2>
      </header>
      <div class="focus"> <a target="_blank" href="[field:arcurl/]"> <img class="thumb" src="[field:litpic/]" alt="[field:title/]"> </a> </div>
      <span class="note"> [field:description function="cn_substr(@me,220)"/]... </span>
      <p class="auth-span"> <span class="muted"> <i class="fa fa-clock-o"> </i> [field:pubdate function='strftime("%Y-%m-%d",@me)'/] </span> <span class="muted"> <i class="fa fa-eye"> </i> [field:click/]℃ </span> <span class="muted">   </span> <span class="muted" id="diggNum105"> <a id="love" class="action" href="javascript:" onclick="javascript:postDigg('good',105)">   </a> </span> </p>
    </article>