<article class="post cate1 auth1">
      <div class="thumb"> <a href="[field:arcurl/]" title="[field:title/]" target="_blank"> <img alt="[field:title/]" src="[field:litpic/]"/> </a> </div>
      <span class="post-cat"><a href="[field:typeurl/]" title="[field:typename/]" target="_blank">[field:typename/]</a></span>
      <h2><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h2>
      <div class="entry loop-entry">
        <p>[field:description function='cn_substr(@me,250)'/]...</p>
      </div>
      <div class="postmeta"> <span><i class="icon-calendar"></i> 日期：[field:pubdate function='strftime("%Y-%m-%d",@me)'/]</span> <span><i class="icon-fire"></i> 浏览：<script src="/plus/count.php?view=yes&aid=[field:id/]&mid=[field:mid/]" type='text/javascript' language="javascript"></script>次</span></div>
    </article>