<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}'><img src='{@me['litpic']}'/></a>\"); ",4,142);
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",150,167);
$z[2]=Array("arcurl","",178,193);
$z[3]=Array("title","",209,223);
$z[4]=Array("pubdate","",272,318);
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",328,342);
$z[6]=Array("description","",374,394);

?>