<?php
$z[0]=Array("field","",99,125);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",169,197);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",200,229);
$z[2][4]['name']="typename";
$z[3]=Array("field","\r\nglobal \$dsql;\r\n\$sql = \"SELECT id From `#@__arctype` WHERE reid='@me' And ishidden<>1 order by sortrank asc limit 0, 100 \";\r\n\$row = \$dsql->GetOne(\$sql);\r\n@me=is_array(\$row)?'class=\"sub-menu\"':'style=\"display:none\"';\r\n",247,515);
$z[3][4]['name']="typeid";
$z[3][4]['runphp']="yes";

?>