<?php
$z[0]=Array("global","\r\n            \$a=\"<li class='right'>\";\r\n            \$b=\"<li>\";\r\n            if ((@me%2)==0 && @me!=30) @me=\$a;\r\n            else  @me=\$b;\r\n            ",0,208);
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",263,278);
$z[2]=Array("title","",287,301);
$z[3]=Array("picname","",313,329);
$z[4]=Array("title","",336,350);
$z[5]=Array("arcurl","",389,404);
$z[6]=Array("title","",413,427);
$z[7]=Array("title","",429,443);
$z[8]=Array("description","",468,518);
$z[8][4]['function']="cn_substr(@me,320)";

?>