<?php
$z[0]=Array("global","",199,231);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("channel"," <a href='[field:typeurl/]'>[field:typename/]</a> ",365,467);
$z[1][4]['type']="son";
$z[1][4]['typeid']="14";
$z[2]=Array("global","",705,726);
$z[2][4]['name']="cfg_qq";
$z[3]=Array("global","",805,837);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("type","[field:typelink /]",989,1040);
$z[4][4]['typeid']="14";
$z[5]=Array("type","[field:typelink /]",1067,1118);
$z[5][4]['typeid']="16";
$z[6]=Array("channel"," <span><a href='[field:typeurl/]'>[field:typename/]</a></span> ",1408,1523);
$z[6][4]['type']="son";
$z[6][4]['typeid']="14";
$z[7]=Array("global","",1621,1653);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1731,1763);
$z[8][4]['name']="cfg_templets_skin";

?>