<?php
$z[0]=Array("arcurl","",109,124);
$z[1]=Array("title","",126,140);
$z[2]=Array("description","",195,245);
$z[2][4]['function']="cn_substr(@me,220)";
$z[3]=Array("writer","",334,349);
$z[4]=Array("click","",428,442);
$z[5]=Array("pubdate","",509,561);
$z[5][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[6]=Array("arcurl","",666,681);
$z[7]=Array("picname","",739,755);
$z[8]=Array("title","",762,776);

?>