<?php
$z[0]=Array("arcurl","",132,147);
$z[1]=Array("title","",185,199);
$z[2]=Array("picname","",212,228);
$z[3]=Array("title","",235,249);
$z[4]=Array("arcurl","",373,388);
$z[5]=Array("title","",413,427);
$z[6]=Array("title","",429,443);
$z[7]=Array("pubdate","",530,579);
$z[7][4]['function']="strftime(\"%m-%d\",@me)";
$z[8]=Array("click","",621,635);
$z[9]=Array("typeurl","",792,808);
$z[10]=Array("typename","",825,842);

?>