<article class="post_box">
    <div class="c-top" id="post-8339">
        <div class="datetime">[field:pubdate function='strftime("%Y年%m月%d日",@me)'/]</div>	
            <header class="tit">
                <h2 class="h1">
                	<a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h2>
                <aside class="iititle">
                	<span><i class="icon-folder-open icon-large"></i> <a href="[field:typeurl/]" title="[field:typename/]" rel="category">[field:typename/]</a></span>
                	<span><i class="icon-eye-open icon-large"></i> 围观[field:click/] 次</span>
                	</aside>
            </header>
    </div>
    <div class="c-con">    
    	<a href="[field:arcurl/]" class="disp_a" title="[field:title/]">	
    		<img src="[field:picname/]" alt="[field:title/]">[field:description function="cn_substr(@me,220)"/]...</a>
    		<a href="[field:arcurl/]" class="more-link" style="width: 15%;">阅读更多</a><div class="cls"></div>
    </div>
    <div class="c-bot">
    <aside class="cb_bq"><i class="icon-tag icon-large"></i></aside>
        <div class="cls"></div>
    </div>
</article>