<li><em class="n[field:global name=autoindex/]">[field:global name=autoindex/] </em>
       <a href="[field:arcurl/]" title="[field:title /]" class="commentimg" target="_blank"><img width="80" height="60" src="[field:litpic/]" alt="[field:title /]"></a>
       <h4><a href="[field:arcurl/]" title="[field:title /]" target="_blank">[field:title /]</a></h4>
       <span>[field:description function="cn_substr(@me,120)"/]..</span>
      </li>