<?php
$z[0]=Array("global","",16,46);
$z[0][4]['name']="autoindex";
$z[1]=Array("global","",48,78);
$z[1][4]['name']="autoindex";
$z[2]=Array("arcurl","",102,117);
$z[3]=Array("title","",126,141);
$z[4]=Array("litpic","",211,226);
$z[5]=Array("title","",233,248);
$z[6]=Array("arcurl","",276,291);
$z[7]=Array("title","",300,315);
$z[8]=Array("title","",333,348);
$z[9]=Array("description","",372,422);
$z[9][4]['function']="cn_substr(@me,120)";

?>