<?php
$z[0]=Array("global","",20,43);
$z[0][4]['name']="cfg_mip";
$z[1]=Array("id","",56,67);
$z[2]=Array("title","",76,91);
$z[3]=Array("title","",131,146);
$z[4]=Array("pubdate","",179,226);
$z[4][4]['function']="MyDate('Y-m-d',@me)";
$z[5]=Array("description","",258,307);
$z[5][4]['function']="cn_substr(@me,70)";
$z[6]=Array("typename","",396,413);
$z[7]=Array("global","",421,444);
$z[7][4]['name']="cfg_mip";
$z[8]=Array("typeid","",459,474);
$z[9]=Array("typename","",496,513);

?>