<div class="blogs">
        <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
        <figure>[field:image/]</figure>
        <ul>
          <p>[field:description/]</p>
          <a href="[field:arcurl/]" target="_blank" class="readmore">阅读全文&gt;&gt;</a>
        </ul>
        <p class="autor"><span>作者：[field:writer/]</span><span>浏览（<a href="[field:arcurl/]">[field:click/]</a>）</span></p>
        <div class="dateview">[field:pubdate function="GetDateMK(@me)"/]</div>
      </div>