<li> <a href="[field:arcurl/]" target="_blank" class="i"><img alt="[field:title/][field:shorttitle/]" src="[field:picname/]" width="86" height="122" /></a>
            <div class="info">
              <h2 class="c0071bc"><a href="[field:arcurl/]" target="_blank">[field:title/][field:shorttitle/]</a></h2>
              <p>主演：[field:authors/]</p>
              <p><b>状态：[field:source/]</b><b>地区：[field:areas/]</b></p>
              <span class="jianjie">[field:description/]...</span> </div>
          </li>