<li> <a class="Themefont Triangle" href="{dede:field name='typeurl'/}" > {dede:field name='typename'/} </a> <span class="TriangleBtn"></span>
                  <ul class="Themebg">
                    {dede:channel type='son' noself='yes'}
                    <li class="Themebghover"> <a class="" href="[field:typelink/]" > [field:typename/] </a> </li>
                    {/dede:channel}
                  </ul>
                </li>