<li class="pr-item pr"><a class="img" href="[field:arcurl/]" target="_blank" title="[field:title/]"><img class="animation" src="[field:picname function='thumb(@me,100,75,true)'/]" alt="[field:title/]" width="100" height="75"></a>
                <div class="pr-list-txt-wrap">
                  <h4><a href="[field:arcurl/]" target="_blank" title="[field:title/]">[field:title/]</a></h4>
                  <p>[field:title/]</p>
                </div>
              </li>