<?php
$z[0]=Array("channel","\r\n<section class=\"graduate-sec2\">\r\n  <div class=\"gra-sec-tit\">\r\n    <h3>[field:typename/]</h3>\r\n    <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">更多</a> </div>\r\n  <ul>\r\n    {dede:arclist orderby ='pubdate' titlelen='38' row='8'}\r\n    <li><a title=\"[field:title/]\" href=\"view.php?aid=[field:id/]\"><i></i>[field:title/]</a></li>\r\n    {/dede:arclist}\r\n  </ul>\r\n</section>\r\n",0,418);

?>