<?php
$z[0]=Array("arcurl","",49,64);
$z[1]=Array("litpic","",76,91);
$z[2]=Array("title","",98,112);
$z[3]=Array("typeurl","",146,162);
$z[4]=Array("typename","",183,200);
$z[5]=Array("typename","",202,219);
$z[6]=Array("arcurl","",248,263);
$z[7]=Array("title","",272,286);
$z[8]=Array("title","",288,302);
$z[9]=Array("pubdate","",374,421);
$z[9][4]['function']="MyDate('Y-m-d',@me)";
$z[10]=Array("arcurl","",481,496);
$z[11]=Array("title","",505,519);
$z[12]=Array("description","",521,571);
$z[12][4]['function']="cn_substr(@me,250)";

?>