<dl>
     <dt><img src="[field:litpic/]" alt="[field:title /]" /><h5>[field:pubdate function="MyDate('m-d',@me)"/] / 浏览量：[field:click/] 次</h5></dt>
     <dd>
      <h3><a href="[field:arcurl/]">[field:title /]</a></h3>
      <span>[field:description function="cn_substr(@me,220)"/]......[详细]</span>
      <h6>[field:id function=GetTags(@me)/]</h6>
      <div class="jw">
       <div class="bshare-custom"><div class="bsPromo bsPromo2"></div><a title="分享到QQ空间" class="bshare-qzone"></a><a title="分享到新浪微博" class="bshare-sinaminiblog"></a><a title="分享到人人网" class="bshare-renren"></a><a title="分享到腾讯微博" class="bshare-qqmb"></a><a title="分享到网易微博" class="bshare-neteasemb"></a><a title="更多平台" class="bshare-more bshare-more-icon more-style-addthis"></a></div><script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/buttonLite.js#style=-1&uuid=cefff51d-26d3-4436-a3f7-2ab64beca899&pophcol=3&lang=zh"></script><script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/bshareC0.js"></script>
      </div>
     </dd>
    </dl>