<?php
$z[0]=Array("global","",131,157);
$z[0][4]['name']="cfg_powerby";
$z[1]=Array("global","",197,221);
$z[1][4]['name']="cfg_beian";
$z[2]=Array("global","",292,324);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",387,419);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",501,533);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",594,626);
$z[5][4]['name']="cfg_templets_skin";

?>