<?php
$z[0]=Array("channelartlist","\r\n        <li class=\"item\">\r\n            <a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n        </li>\r\n",840,1032);
$z[0][4]['typeid']="12,18,14";
$z[1]=Array("global","",1089,1121);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",1185,1217);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1291,1323);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1387,1419);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1488,1520);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1589,1621);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",1688,1720);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1786,1818);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1886,1918);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("global","",1987,2019);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("global","",2092,2124);
$z[11][4]['name']="cfg_templets_skin";

?>