<?php
$z[0]=Array("global","",139,165);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",206,232);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("type","<li id=\"navbar-category-1\"><a href=\"[field:typelink /]\"><i class=\"icon-tasks\"></i> [field:typename /]</a></li>",441,586);
$z[2][4]['typeid']="12";
$z[3]=Array("type","<li id=\"navbar-category-1\"><a href=\"[field:typelink /]\"><i class=\"icon-share\"></i> [field:typename /]</a></li>",600,745);
$z[3][4]['typeid']="13";
$z[4]=Array("type","<li id=\"navbar-category-1\"><a href=\"[field:typelink /]\"><i class=\"icon-desktop\"></i> [field:typename /]</a></li>",759,906);
$z[4][4]['typeid']="14";
$z[5]=Array("type","<li id=\"navbar-page-2\"><a href=\"[field:typelink /]\"><i class=\"icon-comments\"></i> [field:typename /]</a></li>",920,1064);
$z[5][4]['typeid']="15";
$z[6]=Array("type","<li id=\"navbar-page-2\"><a href=\"[field:typelink /]\"><i class=\"icon-comments\"></i> [field:typename /]</a></li>",1077,1221);
$z[6][4]['typeid']="16";

?>