<?php
$z[0]=Array("global","",182,214);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("channelartlist","\r\n            <script type=\"text/javascript\">\r\n                menu.push({\r\n                    'name': '{dede:field name=\"typename\"/}',\r\n                    'enname': '',\r\n                    'url': '{dede:field name=\"typeurl\"/}',\r\n                    'list': []\r\n                });\r\n            </script>\r\n        ",1328,1740);
$z[1][4]['typeid']="12,18,14";
$z[1][4]['currentstyle']="current-menu-item";

?>