<?php
$z[0]=Array("type","[field:typelink /]",126,178);
$z[0][4]['typeid']="5";
$z[1]=Array("type","[field:typename /]",180,232);
$z[1][4]['typeid']="5";
$z[2]=Array("global","",274,300);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",434,460);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("channel","\r\n  <LI><a href=\"[field:typelink/]\" title=\"[field:typename function='substr(@me,0,8)'/]\" >[field:typename function='substr(@me,0,8)'/]</a></LI>\r\n  ",1092,1288);
$z[4][4]['row']="5";
$z[4][4]['type']="top";

?>