<?php
$z[0]=Array("global","",196,223);
$z[0][4]['name']="cfg_indexurl";
$z[1]=Array("global","",351,378);
$z[1][4]['name']="cfg_indexurl";
$z[2]=Array("type","<a href='[field:typelink /]' class=\"transition\" target=\"_blank\">[field:typename /]</a>",449,569);
$z[2][4]['typeid']="1";
$z[3]=Array("type","<a href='[field:typelink /]' class=\"transition\" target=\"_blank\">[field:typename /]</a>",585,705);
$z[3][4]['typeid']="2";
$z[4]=Array("type","<a href='[field:typelink /]' class=\"transition\" target=\"_blank\">[field:typename /]</a>",721,841);
$z[4][4]['typeid']="3";
$z[5]=Array("type","<a href='[field:typelink /]' class=\"transition\" target=\"_blank\">[field:typename /]</a>",857,977);
$z[5][4]['typeid']="4";

?>