<?php
$z[0]=Array("global","",72,97);
$z[0][4]['name']="cfg_wecome";
$z[1]=Array("global","",172,199);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",203,229);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",302,329);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",333,359);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",713,739);
$z[5][4]['name']="cfg_webname";
$z[6]=Array("global","",1315,1340);
$z[6][4]['name']="cfg_hotkey";
$z[7]=Array("channel","\r\n      	<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",1518,1642);
$z[7][4]['type']="top";
$z[7][4]['row']="10";
$z[8]=Array("channel","<a href='[field:typeurl/]'>[field:typename/]</a>",1698,1806);
$z[8][4]['typeid']="1";
$z[8][4]['type']="son";
$z[8][4]['row']="10";
$z[9]=Array("channel","<a href='[field:typeurl/]'>[field:typename/]</a>",1806,1915);
$z[9][4]['type']="son";
$z[9][4]['typeid']="10";
$z[9][4]['row']="10";

?>