<?php
$z[0]=Array("global","",133,160);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",233,260);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",263,289);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",840,867);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",879,904);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",935,961);
$z[5][4]['name']="cfg_webname";
$z[6]=Array("field","",1021,1048);
$z[6][4]['name']="phpurl";
$z[7]=Array("global","",2453,2478);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n      	",2519,2733);
$z[8][4]['type']="top";
$z[8][4]['row']="10";
$z[8][4]['currentstyle']="<li><a href='~typelink~' ~rel~ class='on'>~typename~</a></li>";
$z[9]=Array("global","",2816,2841);
$z[9][4]['name']="cfg_cmsurl";
$z[10]=Array("global","",3023,3048);
$z[10][4]['name']="cfg_cmsurl";
$z[11]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n      	",3089,3303);
$z[11][4]['type']="top";
$z[11][4]['row']="10";
$z[11][4]['currentstyle']="<li><a href='~typelink~' ~rel~ class='on'>~typename~</a></li>";

?>