<?php
$z[0]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",397,639);
$z[0][4]['type']="top";
$z[0][4]['row']="8";
$z[0][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[1]=Array("global","",1299,1324);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n      	",1365,1579);
$z[2][4]['type']="top";
$z[2][4]['row']="10";
$z[2][4]['currentstyle']="<li><a href='~typelink~' ~rel~ class='on'>~typename~</a></li>";

?>