<?php
$z[0]=Array("global","",406,432);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",476,506);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",543,570);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1159,1194);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n        <li><a href=\"[field:lj/]\" target=\"_blank\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/></a></li>\r\n        ",1341,1576);
$z[4][4]['row']="5";
$z[4][4]['titlelen']="60";
$z[4][4]['typeid']="5";
$z[4][4]['addfields']="lj";
$z[4][4]['channelid']="17";
$z[5]=Array("arclist","<h2><span>置顶推荐</span> <a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h2>",1688,1850);
$z[5][4]['row']="5";
$z[5][4]['titlelen']="60";
$z[5][4]['flag']="c";
$z[6]=Array("arclist","\r\n    <article class=\"post cate1 auth1\">\r\n      <div class=\"thumb\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\"> <img alt=\"[field:title/]\" src=\"[field:litpic/]\"/> </a> </div>\r\n      <span class=\"post-cat\"><a href=\"[field:typeurl/]\" title=\"[field:typename/]\" target=\"_blank\">[field:typename/]</a></span>\r\n      <h2><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">[field:title/]</a></h2>\r\n      <div class=\"entry loop-entry\">\r\n        <p>[field:description function='cn_substr(@me,250)'/]...</p>\r\n      </div>\r\n      <div class=\"postmeta\"> <span><i class=\"icon-calendar\"></i> 日期：[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/]</span> <span><i class=\"icon-fire\"></i> 浏览：<script src=\"/plus/count.php?view=yes&aid=[field:id/]&mid=[field:mid/]\" type='text/javascript' language=\"javascript\"></script>次</span></div>\r\n    </article>\r\n    ",1881,2833);
$z[6][4]['row']="15";
$z[6][4]['titlelen']="60";
$z[6][4]['channelid']="1";
$z[7]=Array("include","",2860,2896);
$z[7][4]['filename']="right.htm";
$z[8]=Array("include","",2906,2941);
$z[8][4]['filename']="foot.htm";

?>