<?php
$z[0]=Array("global","",64,90);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",131,158);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",198,228);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",656,691);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n      <div class=\"blogs\">\r\n        <h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n        <figure>[field:image/]</figure>\r\n        <ul>\r\n          <p>[field:description/]</p>\r\n          <a href=\"[field:arcurl/]\" target=\"_blank\" class=\"readmore\">阅读全文&gt;&gt;</a>\r\n        </ul>\r\n        <p class=\"autor\"><span>作者：[field:writer/]</span><span>浏览（<a href=\"[field:arcurl/]\">[field:click/]</a>）</span></p>\r\n        <div class=\"dateview\">[field:pubdate function=\"GetDateMK(@me)\"/]</div>\r\n      </div>\r\n      ",1055,1665);
$z[4][4]['row']="5";
$z[4][4]['orderby']="pubdate";
$z[4][4]['flag']="c";
$z[4][4]['type']="image";
$z[5]=Array("include","",1690,1726);
$z[5][4]['filename']="right.htm";

?>