<?php
$z[0]=Array("arclist","\r\n        <li>\r\n          <div class=\"thumbnail\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\"><img src=\"[field:picname/]\"/></a> </div>\r\n          <p><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">[field:title/]...</a></p>\r\n        </li>\r\n      ",184,548);
$z[0][4]['titlelen']="50";
$z[0][4]['typeid']="top";
$z[0][4]['orderby']="pubdate";
$z[0][4]['row']="5";

?>