<?php
$z[0]=Array("global","",315,341);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",385,415);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",452,479);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",535,567);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",680,712);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",821,853);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",941,973);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",1037,1069);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1142,1174);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1233,1265);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("global","",1860,1892);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("include","",1973,2008);
$z[11][4]['filename']="head.htm";
$z[12]=Array("field","",2155,2184);
$z[12][4]['name']="typename";
$z[13]=Array("channel","\r\n             <a href=\"[field:typelink/]\" >[field:typename/]</a>\r\n             ",2369,2559);
$z[13][4]['type']="son";
$z[13][4]['currentstyle']="<a href='~typelink~' class='thisclass'>~typename~</a>";
$z[14]=Array("list","\r\n     <article class=\"excerpt list5\">\r\n        <p class=\"image-container\"><a target=\"_blank\" class=\"focus\" href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" class=\"thumb\"></a></p>\r\n        <header>\r\n          <h2><a target=\"_blank\" href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h2>\r\n        </header>\r\n        <p class=\"meta\">\r\n          <time><i class=\"fa fa-clock-o\"></i>[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/]</time>\r\n          <span class=\"pv\"><i class=\"fa fa-eye\"></i>浏览:[field:click/]次</span></p>\r\n      </article>\r\n      ",3098,3706);
$z[14][4]['pagesize']="21";
$z[15]=Array("pagelist","",3767,3833);
$z[15][4]['listitem']="index,end,pre,next,pageno";
$z[15][4]['listsize']="3";
$z[16]=Array("include","",3870,3905);
$z[16][4]['filename']="foot.htm";

?>