<?php
$z[0]=Array("field","",155,174);
$z[0][4]['name']="title";
$z[1]=Array("global","",175,201);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",226,255);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",292,351);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",518,540);
$z[4][4]['name']="cfg_mip";
$z[5]=Array("field","",540,561);
$z[5][4]['name']="typeurl";
$z[6]=Array("field","",601,630);
$z[6][4]['name']="position";
$z[7]=Array("field","",710,739);
$z[7][4]['name']="typename";
$z[8]=Array("channelartlist","\r\n<section class=\"graduate-sec2\">\r\n  <div class=\"gra-sec-tit\">\r\n    <h3>{dede:field name='typename'/}</h3>\r\n    <a href=\"listlb.php?tid={dede:field name='id'/}\" title=\"{dede:field name='typename'/}\">更多</a> </div>\r\n  <ul>\r\n    {dede:arclist orderby ='pubdate' titlelen='38' row='8'}\r\n    <li><a title=\"[field:title/]\" href=\"view.php?aid=[field:id/]\"><i></i>[field:title/]</a></li>\r\n    {/dede:arclist}\r\n  </ul>\r\n</section>\r\n",758,1247);
$z[8][4]['typeid']="0";
$z[8][4]['row']="9";
$z[9]=Array("global","",1401,1427);
$z[9][4]['name']="cfg_powerby";
$z[10]=Array("global","",1440,1464);
$z[10][4]['name']="cfg_beian";

?>