<?php
$z[0]=Array("arclist","\r\n        <li>\r\n          <div class=\"sideshow\"><a href=\"[field:arcurl/]\" target=\"_ablank\"  title=\"[field:title/]\"> <img width='80' height='60' src='[field:picname/]' class='icon wp-post-image' alt='[field:title/]' title='[field:title/]' /> </a> <a href=\"[field:arcurl/]\" target=\"_ablank\"  title=\"[field:title/]\"> [field:title/] </a> <span class=\"datetime\"> [field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/] </span> </div>\r\n        </li>\r\n        ",121,631);
$z[0][4]['titlelen']="80";
$z[0][4]['flag']="a";
$z[0][4]['row']="5";
$z[1]=Array("arclist","\r\n        <li>\r\n          <div class=\"sideshow\"><a href=\"[field:arcurl/]\" target=\"_ablank\"  title=\"[field:title/]\"> <img width='80' height='60' src='[field:picname/]' class='icon wp-post-image' alt='[field:title/]' title='[field:title/]' /> </a> <a href=\"[field:arcurl/]\" target=\"_ablank\"  title=\"[field:title/]\"> [field:title/] </a> <span class=\"datetime\"> [field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/] </span> </div>\r\n        </li>\r\n        ",736,1252);
$z[1][4]['titlelen']="80";
$z[1][4]['orderby']="click";
$z[1][4]['row']="8";

?>