<?php
$z[0]=Array("channel","\r\n        <li><a title=\"[field:typename/]\" href=\"[field:typelink/]\" target=\"_blank\"><span>[field:typename/]</span><em></em></a></li>\r\n        ",112,323);
$z[0][4]['type']="son";
$z[0][4]['noself']="yes";
$z[1]=Array("arclist","\r\n        <li> <a title=\"[field:typename/]\" href=\"[field:typeurl/]\" target=\"_blank\" class=\"tit\">[field:typename/]</a> <a title=\"[field:title/]\" href=\"[field:arcurl/]\" target=\"_blank\" class=\"detial\">[field:title/]</a> </li>\r\n        ",433,775);
$z[1][4]['orderby']="click";
$z[1][4]['titlelen']="38";
$z[1][4]['row']="10";
$z[1][4]['noself']="yes";
$z[2]=Array("arclist","\r\n        <li> <a title=\"[field:typename/]\" href=\"[field:typeurl/]\" target=\"_blank\" class=\"tit\">[field:typename/]</a> <a title=\"[field:title/]\" href=\"[field:arcurl/]\" target=\"_blank\" class=\"detial\">[field:title/]</a> </li>\r\n        ",885,1229);
$z[2][4]['orderby']="pubdate";
$z[2][4]['titlelen']="38";
$z[2][4]['row']="10";
$z[2][4]['noself']="yes";

?>