<?php
$z[0]=Array("arclist","\r\n       <li><em class=\"n[field:global name=autoindex/]\">[field:global name=autoindex/] </em>\r\n       <a href=\"[field:arcurl/]\" title=\"[field:title /]\" class=\"commentimg\" target=\"_blank\"><img width=\"80\" height=\"60\" src=\"[field:litpic/]\" alt=\"[field:title /]\"></a>\r\n       <h4><a href=\"[field:arcurl/]\" title=\"[field:title /]\" target=\"_blank\">[field:title /]</a></h4>\r\n       <span>[field:description function=\"cn_substr(@me,120)\"/]..</span>\r\n      </li>\r\n     ",108,641);
$z[0][4]['titlelen']="35";
$z[0][4]['row']="5";
$z[0][4]['flag']="c";
$z[0][4]['typeid']="all";
$z[1]=Array("arclist","\r\n     <li>\r\n      <h4><a href=\"[field:arcurl/]\" title=\"[field:title /]\" target=\"_blank\">[field:title /]</a></h4>\r\n       <div class=\"wiget\">\r\n        <a href=\"[field:arcurl/]\" > <img width=\"120\" height=\"90\" class=\"dream-img\" src=\"[field:litpic/]\" alt=\"[field:title /]\"></a>    \r\n       <div class=\"dreamer-info\"><p>[field:description function=\"cn_substr(@me,120)\"/]..</p></div>\r\n       </div>\r\n      </li>    \r\n     ",740,1219);
$z[1][4]['titlelen']="35";
$z[1][4]['row']="4";
$z[1][4]['typeid']="3";
$z[2]=Array("flink","[field:link /]",1317,1406);
$z[2][4]['row']="24";
$z[2][4]['type']="text";
$z[2][4]['titlelen']="26";
$z[2][4]['linktype']="2";

?>