<?php
$z[0]=Array("arclist","\r\n      <li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <span class=\"thumbnail\"> <img src=\"[field:litpic/]\" alt=\"[field:title/]\"> </span> <span class=\"text\">[field:title/] </span> <span class=\"muted\"> [field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/] </span>  </a> </li>\r\n      ",1549,1905);
$z[0][4]['titlelen']="80";
$z[0][4]['orderby']="pubdate";
$z[0][4]['row']="8";
$z[1]=Array("arclist","\r\n      <li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <span class=\"thumbnail\"> <img src=\"[field:litpic/]\" alt=\"[field:title/]\"> </span> <span class=\"text\"> [field:title/] </span> <span class=\"muted\"> [field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/] </span>  </a> </li>\r\n      ",2219,2578);
$z[1][4]['titlelen']="80";
$z[1][4]['orderby']="rand";
$z[1][4]['limit']="0,1";
$z[2]=Array("arclist","\r\n      <li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <span class=\"thumbnail\"> <img src=\"[field:litpic/]\" alt=\"[field:title/]\"> </span> <span class=\"text\"> [field:title/] </span> <span class=\"muted\"> [field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/] </span>  </a> </li>\r\n      ",2587,2946);
$z[2][4]['titlelen']="80";
$z[2][4]['orderby']="rand";
$z[2][4]['limit']="1,9";

?>