<?php
$z[0]=Array("arclist","\r\n        <li><span class=\"li-icon li-icon-[field:global.autoindex/]\">[field:global.autoindex/]</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n        ",228,458);
$z[0][4]['titlelen']="80";
$z[0][4]['orderby']="click";
$z[0][4]['row']="10";
$z[1]=Array("arclist","\r\n        <li><span class=\"li-icon li-icon-[field:global.autoindex/]\">[field:global.autoindex/]</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n        ",725,947);
$z[1][4]['titlelen']="80";
$z[1][4]['flag']="c";
$z[1][4]['row']="10";

?>