<?php
$z[0]=Array("arclist","\r\n			<li>\r\n                    <span class=\"num top3\">[field:global.autoindex/]</span>\r\n                    <a href=\"[field:arcur/]\" title=\"[field:title/]\">[field:title/]</a>\r\n                    <span class=\"tm\">[field:pubdate function='strftime(\"%m-%d\",@me)'/]</span>\r\n                </li>\r\n",241,573);
$z[0][4]['row']="10";
$z[1]=Array("arclist","\r\n			<li>\r\n                    <span class=\"num top3\">[field:global.autoindex/]</span>\r\n                    <a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a>\r\n                    <span class=\"tm\">[field:pubdate function='strftime(\"%m月%d日\",@me)'/]</span>\r\n                </li>\r\n            ",866,1233);
$z[1][4]['row']="10";
$z[1][4]['orderby']="click";

?>