<?php
$z[0]=Array("myad","",154,181);
$z[0][4]['name']="youceyi";
$z[1]=Array("arclist","\r\n      <li><a href=\"[field:arcurl/]\">[field:title/]</a> </li>\r\n      ",627,757);
$z[1][4]['row']="8";
$z[1][4]['orderby']="rand";
$z[1][4]['titlelen']="67";
$z[2]=Array("myad","",856,883);
$z[2][4]['name']="youceer";
$z[3]=Array("flink"," [field:link /] ",1018,1105);
$z[3][4]['row']="24";
$z[3][4]['type']="text";
$z[3][4]['titlelen']="24";
$z[3][4]['typeid']="0";

?>