<?php
$z[0]=Array("global","",181,206);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("arclist","\r\n        <li>\r\n          <div class=\"thumb\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/></a></div>\r\n          <div class=\"hot-title\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></div>\r\n          <div class=\"hot-time\"><i class=\"icon-time\"></i> [field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/]</div>\r\n        </li>\r\n        ",512,1009);
$z[1][4]['row']="5";
$z[1][4]['titlelen']="60";
$z[1][4]['orderby']="rand";
$z[1][4]['typeid']="top";
$z[1][4]['channelid']="1";
$z[2]=Array("arclist","\r\n        <li>\r\n          <div class=\"thumb\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/></a></div>\r\n          <div class=\"hot-title\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></div>\r\n          <div class=\"hot-time\"><i class=\"icon-time\"></i> [field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/]</div>\r\n        </li>\r\n        ",1165,1647);
$z[2][4]['row']="5";
$z[2][4]['titlelen']="60";
$z[2][4]['typeid']="top";
$z[2][4]['channelid']="1";

?>