<?php
$z[0]=Array("arclist","\r\n      <li> <a href=\"[field:arcurl/]\">[field:title/]</a> </li>\r\n      ",95,221);
$z[0][4]['orderby']="pubdate";
$z[0][4]['row']="8";
$z[1]=Array("arclist","\r\n        <li class=\"post\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <img src=\"[field:picname/]\"  alt=\"[field:title/]\">\r\n          <h4>[field:title/]</h4>\r\n          </a> </li>\r\n        ",814,1056);
$z[1][4]['flag']="c";
$z[1][4]['row']="6";

?>