<?php
$z[0]=Array("global","",191,223);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("arclist","\r\n        <li>\r\n          <div class=\"tab-item-thumbnail\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n            <div class=\"thumb-img\"> <img src=\"[field:picname/]\" /> <span><i class=\"fa fa-plus\"></i></span> </div>\r\n            </a> </div>\r\n          <div class=\"tab-item-inner group\">\r\n            <p class=\"tab-item-title\"><a href=\"[field:arcurl/]\"  title=\"[field:title/]\">[field:title/]</a></p>\r\n            <span class=\"tab-item-date\">[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'] </span>&nbsp; <span class=\"tab-item-category\"><a href=\"[field:typeurl/]\" >[field:typename/]</a></span> </div>\r\n        </li>\r\n        ",1017,1708);
$z[1][4]['row']="10";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("arclist","\r\n        <li>\r\n          <div class=\"tab-item-thumbnail\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n            <div class=\"thumb-img\"> <img src=\"[field:picname/]\" /> <span><i class=\"fa fa-plus\"></i></span> </div>\r\n            </a> </div>\r\n          <div class=\"tab-item-inner group\">\r\n            <p class=\"tab-item-title\"><a href=\"[field:arcurl/]\"  title=\"[field:title/]\">[field:title/]</a></p>\r\n            <span class=\"tab-item-date\">[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'] </span>&nbsp; <span class=\"tab-item-category\"><a href=\"[field:typeurl/]\" >[field:typename/]</a></span> </div>\r\n        </li>\r\n         ",1897,2596);
$z[2][4]['row']="10";
$z[2][4]['orderby']="click";
$z[2][4]['flag']="c";
$z[3]=Array("arclist"," \r\n        <li>\r\n          <div class=\"tab-item-thumbnail\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n            <div class=\"thumb-img\"> <img src=\"[field:picname/]\" /> <span><i class=\"fa fa-plus\"></i></span> </div>\r\n            </a> </div>\r\n          <div class=\"tab-item-inner group\">\r\n            <p class=\"tab-item-title\"><a href=\"[field:arcurl/]\"  title=\"[field:title/]\">[field:title/]</a></p>\r\n            <span class=\"tab-item-date\">[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/] </span>&nbsp; <span class=\"tab-item-category\"><a href=\"[field:typeurl/]\" >[field:typename/]</a></span> </div>\r\n        </li>\r\n        ",2784,3473);
$z[3][4]['orderby']="rand";
$z[3][4]['row']="9";

?>