<?php
$z[0]=Array("arclist","\r\n	<li><a href=\"[field:arclist/]\" title=\"[field:title/]\">[field:title/]</a></li>\r\n  ",428,559);
$z[0][4]['flag']="c";
$z[0][4]['row']="12";
$z[1]=Array("arclist","\r\n	<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></li>\r\n",901,1036);
$z[1][4]['orderby']="click";
$z[1][4]['row']="12";
$z[2]=Array("arclist","\r\n	<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></li>\r\n  ",1161,1282);
$z[2][4]['row']="10";

?>