<?php
$z[0]=Array("arclist","\r\n     <li>\r\n        <div class=\"widget-thumb\"> <a class=\"post-thumbnail\" href=\"[field:arcurl/]\" title=\"[field:title/]\" rel=\"bookmark\"><img class=\"lazy\" src=\"[field:picname/]\" style=\"height:45px; width:45px\"></a> <a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a><span class=\"date\">[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/]</span> </div>\r\n      </li>\r\n      ",849,1303);
$z[0][4]['titlelen']="80";
$z[0][4]['orderby']="pubdate";
$z[0][4]['row']="8";
$z[1]=Array("arclist","\r\n        <li>\r\n          <div class=\"widget-thumb\"> <a class=\"post-thumbnail\" href=\"[field:arcurl/]\" title=\"[field:title/]\" rel=\"bookmark\"><img class=\"lazy\" src=\"[field:picname/]\" style=\"height:45px; width:45px\"></a> <a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a><span class=\"date\">[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/]</span> </div>\r\n        </li>\r\n        ",1619,2074);
$z[1][4]['titlelen']="80";
$z[1][4]['flag']="a";
$z[1][4]['row']="8";

?>