<?php
$z[0]=Array("global","",254,309);
$z[0][4]['name']="keyword";
$z[0][4]['function']="RemoveXSS(@me)";
$z[1]=Array("global","",322,348);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",370,402);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("include","",733,770);
$z[3][4]['filename']="header.htm";
$z[4]=Array("global","",929,984);
$z[4][4]['name']="keyword";
$z[4][4]['function']="RemoveXSS(@me)";
$z[5]=Array("list","\r\n          <li>\r\n          	<h1 class=\"c0071bc\"><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/][field:shorttitle/]</a></h1>\r\n            <p>[field:description/]...</p>\r\n          </li>\r\n          ",1067,1310);
$z[5][4]['pagesize']="18";
$z[6]=Array("pagelist","",1408,1437);
$z[6][4]['listsize']="4";
$z[7]=Array("likewords","",1628,1654);
$z[7][4]['num']="14";
$z[8]=Array("include","",1838,1875);
$z[8][4]['filename']="footer.htm";

?>