<?php
$z[0]=Array("global","",106,134);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","",372,398);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1279,1314);
$z[2][4]['filename']="head.htm";
$z[3]=Array("myad","",1385,1411);
$z[3][4]['name']="toppic";
$z[4]=Array("global","",1568,1623);
$z[4][4]['name']="keyword";
$z[4][4]['function']="RemoveXSS(@me)";
$z[5]=Array("list","\r\n      <section class=\"section wow fadeIn\">\r\n        <div class=\"thumbnail\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\"><img src=\"[field:picname/]\" alt=\"[field:title/]\"/></a> </div>\r\n        <h2><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">[field:title/]</a></h2>\r\n        <div class=\"postmeta\"> <span><i class=\"icon-user-circle-o\"></i> <a>[field:writer/]</a></span> <span><i class=\"icon-calendar\"></i>\r\n          <time>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</time>\r\n          </span> <span><i class=\"icon-eye\"></i> [field:click/]</span></div>\r\n        <div class=\"excerpt\">\r\n          <p> [field:description function=\"cn_substr(@me,320)\"/]...</p>\r\n        </div>\r\n      </section>\r\n      ",1665,2443);
$z[5][4]['pagesize']="6";
$z[6]=Array("pagelist","",2478,2544);
$z[6][4]['listitem']="index,end,pre,next,pageno";
$z[6][4]['listsize']="2";
$z[7]=Array("include","",2578,2613);
$z[7][4]['filename']="left.htm";
$z[8]=Array("myad","",2649,2677);
$z[8][4]['name']="footepic";
$z[9]=Array("include","",2804,2841);
$z[9][4]['filename']="footer.htm";

?>